import { Entity } from '../../../shared/domain/entity.base';
import { DocumentType } from './document-type.vo';
import { InvalidHealthDocumentError } from './health-document.errors';

const MAX_TAGS = 20;

/** Metadata describing a scanned document, validated before any upload. */
export interface HealthDocumentMetadata {
  documentType: string;
  title: string;
  documentDate: Date;
  tags?: string[];
}

/** Data required to register a newly stored document. */
export interface CreateHealthDocumentProps extends HealthDocumentMetadata {
  petId: string;
  householdId: string;
  storageFileId: string;
  mimeType: string;
  sizeBytes: number;
}

/** Full snapshot of a persisted document, used to rebuild it. */
export interface HealthDocumentSnapshot {
  id: string;
  petId: string;
  householdId: string;
  storageFileId: string;
  documentType: string;
  title: string;
  documentDate: Date;
  tags: string[];
  mimeType: string;
  sizeBytes: number;
  createdAt: Date;
  updatedAt: Date;
}

/**
 * Rich `HealthDocument` entity: metadata of a scanned health document whose
 * bytes live in an external storage (see the `DocumentStorage` port). It only
 * references the other contexts (`petId`, `householdId`) and the stored file
 * (`storageFileId`) by identifier.
 */
export class HealthDocument extends Entity {
  private readonly _petId: string;
  private readonly _householdId: string;
  private readonly _storageFileId: string;
  private _documentType: DocumentType;
  private _title: string;
  private _documentDate: Date;
  private _tags: string[];
  private readonly _mimeType: string;
  private readonly _sizeBytes: number;
  private readonly _createdAt: Date;
  private _updatedAt: Date;

  private constructor(props: HealthDocumentSnapshot) {
    super(props.id);
    this._petId = props.petId;
    this._householdId = props.householdId;
    this._storageFileId = props.storageFileId;
    this._documentType = DocumentType.create(props.documentType);
    this._title = props.title;
    this._documentDate = props.documentDate;
    this._tags = props.tags;
    this._mimeType = props.mimeType;
    this._sizeBytes = props.sizeBytes;
    this._createdAt = props.createdAt;
    this._updatedAt = props.updatedAt;
  }

  /** Creates a new document; identity and timestamps generated by the domain. */
  static create(props: CreateHealthDocumentProps): HealthDocument {
    const now = new Date();
    HealthDocument.assertDocumentDate(props.documentDate);
    return new HealthDocument({
      id: globalThis.crypto.randomUUID(),
      petId: HealthDocument.requireId(props.petId, 'petId'),
      householdId: HealthDocument.requireId(props.householdId, 'householdId'),
      storageFileId: HealthDocument.requireId(
        props.storageFileId,
        'storageFileId',
      ),
      documentType: props.documentType,
      title: HealthDocument.normalizeTitle(props.title),
      documentDate: props.documentDate,
      tags: HealthDocument.normalizeTags(props.tags),
      mimeType: HealthDocument.requireId(props.mimeType, 'mimeType'),
      sizeBytes: HealthDocument.normalizeSize(props.sizeBytes),
      createdAt: now,
      updatedAt: now,
    });
  }

  /**
   * Validates user-provided metadata without creating the entity. Lets the
   * upload use case fail fast BEFORE paying for the remote file upload; the
   * same rules run again inside `create`.
   */
  static validateMetadata(metadata: HealthDocumentMetadata): void {
    DocumentType.create(metadata.documentType);
    HealthDocument.normalizeTitle(metadata.title);
    HealthDocument.assertDocumentDate(metadata.documentDate);
    HealthDocument.normalizeTags(metadata.tags);
  }

  /** Rebuilds an entity from persistence (no id generation). */
  static fromSnapshot(snapshot: HealthDocumentSnapshot): HealthDocument {
    return new HealthDocument(snapshot);
  }

  toSnapshot(): HealthDocumentSnapshot {
    return {
      id: this.id,
      petId: this._petId,
      householdId: this._householdId,
      storageFileId: this._storageFileId,
      documentType: this._documentType.toString(),
      title: this._title,
      documentDate: this._documentDate,
      tags: [...this._tags],
      mimeType: this._mimeType,
      sizeBytes: this._sizeBytes,
      createdAt: this._createdAt,
      updatedAt: this._updatedAt,
    };
  }

  get petId(): string {
    return this._petId;
  }

  get householdId(): string {
    return this._householdId;
  }

  get storageFileId(): string {
    return this._storageFileId;
  }

  get documentType(): string {
    return this._documentType.toString();
  }

  get title(): string {
    return this._title;
  }

  get documentDate(): Date {
    return this._documentDate;
  }

  get tags(): string[] {
    return [...this._tags];
  }

  get mimeType(): string {
    return this._mimeType;
  }

  get sizeBytes(): number {
    return this._sizeBytes;
  }

  get createdAt(): Date {
    return this._createdAt;
  }

  get updatedAt(): Date {
    return this._updatedAt;
  }

  private static normalizeTitle(title: string): string {
    const trimmed = title?.trim() ?? '';
    if (trimmed.length === 0) {
      throw new InvalidHealthDocumentError('The document title is required.');
    }
    return trimmed;
  }

  /** Trims tags, drops empties and case-insensitive duplicates. */
  private static normalizeTags(tags: string[] | undefined): string[] {
    const normalized: string[] = [];
    const seen = new Set<string>();
    for (const tag of tags ?? []) {
      const trimmed = tag.trim();
      const key = trimmed.toLowerCase();
      if (trimmed.length === 0 || seen.has(key)) {
        continue;
      }
      seen.add(key);
      normalized.push(trimmed);
    }
    if (normalized.length > MAX_TAGS) {
      throw new InvalidHealthDocumentError(
        `A document cannot carry more than ${MAX_TAGS} tags.`,
      );
    }
    return normalized;
  }

  private static normalizeSize(sizeBytes: number): number {
    if (!Number.isInteger(sizeBytes) || sizeBytes <= 0) {
      throw new InvalidHealthDocumentError(
        'The file size must be a positive number of bytes.',
      );
    }
    return sizeBytes;
  }

  private static requireId(value: string, field: string): string {
    if (!value || value.trim().length === 0) {
      throw new InvalidHealthDocumentError(`The « ${field} » is required.`);
    }
    return value;
  }

  private static assertDocumentDate(documentDate: Date): void {
    if (
      !(documentDate instanceof Date) ||
      Number.isNaN(documentDate.getTime())
    ) {
      throw new InvalidHealthDocumentError('The document date is invalid.');
    }
    if (documentDate.getTime() > Date.now()) {
      throw new InvalidHealthDocumentError(
        'The document date cannot be in the future.',
      );
    }
  }
}
