import { Entity } from '../../../shared/domain/entity.base';
import {
  DocumentPage,
  type DocumentPageSnapshot,
  type NewPageData,
} from './document-page.entity';
import { DocumentType } from './document-type.vo';
import { InvalidHealthDocumentError } from './health-document.errors';

const MAX_TAGS = 20;

/** Metadata describing a scanned document, validated before any upload. */
export interface HealthDocumentMetadata {
  documentType: string;
  title: string;
  documentDate: Date;
  tags?: string[];
}

/** Data required to create a new multi-page document. */
export interface CreateHealthDocumentProps extends HealthDocumentMetadata {
  petId: string;
  householdId: string;
  /** User whose storage account holds every page (the member who scanned). */
  uploaderUserId: string;
  /** Ordered pages; their `position` (1..N) follows this array order. */
  pages: NewPageData[];
}

/** Full snapshot of a persisted document, used to rebuild it. */
export interface HealthDocumentSnapshot {
  id: string;
  petId: string;
  householdId: string;
  uploaderUserId: string;
  documentType: string;
  title: string;
  documentDate: Date;
  tags: string[];
  pages: DocumentPageSnapshot[];
  createdAt: Date;
  updatedAt: Date;
}

/**
 * Rich `HealthDocument` aggregate root: metadata of a scanned health document
 * plus an ordered collection of `DocumentPage`s, whose bytes live in an
 * external storage (see the `DocumentStorage` port). It references the other
 * contexts (`petId`, `householdId`) and stored files by identifier only.
 *
 * Aggregate invariants, enforced here rather than only by DB constraints:
 * a document always has ≥ 1 page, and page positions are contiguous and
 * ordered starting at 1 (1, 2, …, N — no gaps). All page mutations go through
 * the root: nothing outside creates, appends or removes a page directly.
 */
export class HealthDocument extends Entity {
  private readonly _petId: string;
  private readonly _householdId: string;
  private readonly _uploaderUserId: string;
  private _documentType: DocumentType;
  private _title: string;
  private _documentDate: Date;
  private _tags: string[];
  private _pages: DocumentPage[];
  private readonly _createdAt: Date;
  private _updatedAt: Date;

  private constructor(props: HealthDocumentSnapshot) {
    super(props.id);
    this._petId = props.petId;
    this._householdId = props.householdId;
    this._uploaderUserId = props.uploaderUserId;
    this._documentType = DocumentType.create(props.documentType);
    this._title = props.title;
    this._documentDate = props.documentDate;
    this._tags = props.tags;
    this._pages = HealthDocument.sortAndAssertContiguous(
      props.pages.map((page) => DocumentPage.fromSnapshot(page)),
    );
    this._createdAt = props.createdAt;
    this._updatedAt = props.updatedAt;
  }

  /**
   * Creates a new document from a batch of pages; identity and timestamps are
   * generated by the domain. The page list must not be empty — a document is
   * meaningless without at least one page — and positions are assigned 1..N
   * from the input order.
   */
  static create(props: CreateHealthDocumentProps): HealthDocument {
    const now = new Date();
    HealthDocument.assertDocumentDate(props.documentDate);
    HealthDocument.assertNonEmpty(props.pages);
    return new HealthDocument({
      id: globalThis.crypto.randomUUID(),
      petId: HealthDocument.requireId(props.petId, 'petId'),
      householdId: HealthDocument.requireId(props.householdId, 'householdId'),
      uploaderUserId: HealthDocument.requireId(
        props.uploaderUserId,
        'uploaderUserId',
      ),
      documentType: props.documentType,
      title: HealthDocument.normalizeTitle(props.title),
      documentDate: props.documentDate,
      tags: HealthDocument.normalizeTags(props.tags),
      pages: props.pages.map((data, index) =>
        DocumentPage.create(data, index + 1).toSnapshot(),
      ),
      createdAt: now,
      updatedAt: now,
    });
  }

  /**
   * Validates user-provided metadata without creating the entity. Lets the
   * create use case fail fast BEFORE paying for the remote uploads; the same
   * rules run again inside `create`.
   */
  static validateMetadata(metadata: HealthDocumentMetadata): void {
    DocumentType.create(metadata.documentType);
    HealthDocument.normalizeTitle(metadata.title);
    HealthDocument.assertDocumentDate(metadata.documentDate);
    HealthDocument.normalizeTags(metadata.tags);
  }

  /** Rebuilds an entity from persistence (no id generation). */
  static fromSnapshot(snapshot: HealthDocumentSnapshot): HealthDocument {
    return new HealthDocument(snapshot);
  }

  toSnapshot(): HealthDocumentSnapshot {
    return {
      id: this.id,
      petId: this._petId,
      householdId: this._householdId,
      uploaderUserId: this._uploaderUserId,
      documentType: this._documentType.toString(),
      title: this._title,
      documentDate: this._documentDate,
      tags: [...this._tags],
      pages: this._pages.map((page) => page.toSnapshot()),
      createdAt: this._createdAt,
      updatedAt: this._updatedAt,
    };
  }

  /**
   * Appends a batch of pages after the current last one, assigning positions
   * N+1 … N+k from the input order. Rejects an empty batch — appending nothing
   * is a caller mistake, not a no-op.
   */
  appendPages(newPages: NewPageData[]): DocumentPage[] {
    HealthDocument.assertNonEmpty(newPages);
    const start = this._pages.length;
    const appended = newPages.map((data, index) =>
      DocumentPage.create(data, start + index + 1),
    );
    this._pages = [...this._pages, ...appended];
    this._updatedAt = new Date();
    return appended;
  }

  /** Recategorizes the document (invalid types are rejected by the VO). */
  changeDocumentType(raw: string): void {
    this._documentType = DocumentType.create(raw);
    this._updatedAt = new Date();
  }

  get petId(): string {
    return this._petId;
  }

  get householdId(): string {
    return this._householdId;
  }

  get uploaderUserId(): string {
    return this._uploaderUserId;
  }

  get documentType(): string {
    return this._documentType.toString();
  }

  get title(): string {
    return this._title;
  }

  get documentDate(): Date {
    return this._documentDate;
  }

  get tags(): string[] {
    return [...this._tags];
  }

  /** The ordered pages of the document (a copy; mutate via the root only). */
  get pages(): DocumentPage[] {
    return [...this._pages];
  }

  /** Looks up one of the document's pages by its id, if it belongs here. */
  findPage(pageId: string): DocumentPage | undefined {
    return this._pages.find((page) => page.id === pageId);
  }

  get pageCount(): number {
    return this._pages.length;
  }

  get createdAt(): Date {
    return this._createdAt;
  }

  get updatedAt(): Date {
    return this._updatedAt;
  }

  private static assertNonEmpty(pages: NewPageData[]): void {
    if (pages.length === 0) {
      throw new InvalidHealthDocumentError(
        'A document must have at least one page.',
      );
    }
  }

  /**
   * Orders the pages by position and enforces the contiguity invariant
   * (1, 2, …, N with no gaps or duplicates). A violation means the persisted
   * data is corrupt — fail loudly rather than render a broken document.
   */
  private static sortAndAssertContiguous(
    pages: DocumentPage[],
  ): DocumentPage[] {
    HealthDocument.assertNonEmpty(pages);
    const ordered = [...pages].sort((a, b) => a.position - b.position);
    ordered.forEach((page, index) => {
      if (page.position !== index + 1) {
        throw new InvalidHealthDocumentError(
          `Document page positions must be contiguous starting at 1 (got ${page.position} at index ${index}).`,
        );
      }
    });
    return ordered;
  }

  private static normalizeTitle(title: string): string {
    const trimmed = title?.trim() ?? '';
    if (trimmed.length === 0) {
      throw new InvalidHealthDocumentError('The document title is required.');
    }
    return trimmed;
  }

  /** Trims tags, drops empties and case-insensitive duplicates. */
  private static normalizeTags(tags: string[] | undefined): string[] {
    const normalized: string[] = [];
    const seen = new Set<string>();
    for (const tag of tags ?? []) {
      const trimmed = tag.trim();
      const key = trimmed.toLowerCase();
      if (trimmed.length === 0 || seen.has(key)) {
        continue;
      }
      seen.add(key);
      normalized.push(trimmed);
    }
    if (normalized.length > MAX_TAGS) {
      throw new InvalidHealthDocumentError(
        `A document cannot carry more than ${MAX_TAGS} tags.`,
      );
    }
    return normalized;
  }

  private static requireId(value: string, field: string): string {
    if (!value || value.trim().length === 0) {
      throw new InvalidHealthDocumentError(`The « ${field} » is required.`);
    }
    return value;
  }

  private static assertDocumentDate(documentDate: Date): void {
    if (
      !(documentDate instanceof Date) ||
      Number.isNaN(documentDate.getTime())
    ) {
      throw new InvalidHealthDocumentError('The document date is invalid.');
    }
    if (documentDate.getTime() > Date.now()) {
      throw new InvalidHealthDocumentError(
        'The document date cannot be in the future.',
      );
    }
  }
}
